server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_study?Servertimezone=Asia/Shanghai&CharacterEncoding=UTF-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:com/wx/mapper/*.xml
  type-aliases-package: com.wx.entity
#  todo springboot日志还得研究
#logging:
#  level: debug
